[project]
name = "json_to_many"
version = "0.1.0"
description = "A utility package to convert JSON data to multiple formats like XML, Markdown, CSV, etc."
readme = "README.md"
license = { file = "LICENSE" }

requires-python = ">=3.10,<3.13"
authors = [{ name = "ananthanandanan", email = "ananthanandanan@gmail.com" }]
keywords = ["csv", "converter", "json", "markdown", "xml"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Markup",
    "Topic :: Utilities",
]
dependencies = ["xmltodict>=0.13.0,<0.14"]

[project.urls]
Homepage = "https://github.com/ananthanandanan/Json_To_Many"
Repository = "https://github.com/ananthanandanan/Json_To_Many"
Documentation = "https://github.com/ananthanandanan/Json_To_Many/tree/main?tab=readme-ov-file#quick-start"
"Bug Reports" = "https://github.com/ananthanandanan/Json_To_Many/issues"

[dependency-groups]
dev = ["pytest>=8.3.3,<9", "ruff>=0.4.9,<0.5", "twine>=6.1.0"]

[tool.hatch.build.targets.sdist]
include = ["LICENSE", "README.md", "src/json_to_many"]
exclude = ["docs/*", "examples/*", "tests/*"]

[tool.hatch.build.targets.wheel]
include = ["LICENSE", "README.md", "src/json_to_many"]
exclude = ["docs/*", "examples/*", "tests/*"]

[tool.hatch.build.targets.wheel.sources]
"src/json_to_many" = "json_to_many"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
