[project]
name = "json_to_many"
version = "0.1.0"
description = "A utility package to convert JSON data to multiple formats like XML, Markdown, CSV, etc."
readme = "README.md"
requires-python = ">=3.10,<3.13"
authors = [{ name = "ananthanandanan", email = "ananthanandanan@gmail.com" }]
keywords = ["csv", "converter", "json", "markdown", "xml"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = ["xmltodict>=0.13.0,<0.14"]

[dependency-groups]
dev = ["pytest>=8.3.3,<9", "ruff>=0.4.9,<0.5"]

[tool.hatch.build.targets.sdist]
include = ["LICENSE", "README.md", "src/json_to_many"]
exclude = ["docs/*", "examples/*", "tests/*"]

[tool.hatch.build.targets.wheel]
include = ["LICENSE", "README.md", "src/json_to_many"]
exclude = ["docs/*", "examples/*", "tests/*"]

[tool.hatch.build.targets.wheel.sources]
"src/json_to_many" = "json_to_many"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
