[tool.poetry]
name = "json_to_many"
version = "0.1.0"
description = "A utility package to convert JSON data to multiple formats like XML, Markdown, CSV, etc."
authors = ["ananthanandanan <ananthanandanan@gmail.com>"]
readme = "README.md"
keywords = ["json", "converter", "xml", "markdown", "csv"]
packages = [{include = "json_to_many", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
xmltodict = "^0.13.0"
pytest = "^8.3.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.9"

[tool.pytest.ini_options]
pythonpath = ["src"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
